name: ros-app
version: '1.0'
grade: stable
confinement: devmode
summary: ROS App Snap
description: Contains talker/listener ROS packages and a .launch file.
passthrough:
  base: core18-ros

apps:
  launch-project:
    command: run-system
    plugs: [network, network-bind]

parts:
  ros-app:
    plugin: catkin
    rosdistro: kinetic
    include-roscore: false
    underlay:
      # Build-time location of the underlay
      build-path: $SNAPCRAFT_PART_INSTALL/opt/ros/kinetic

      # Run-time location of the underlay
      run-path: /opt/ros/kinetic
    catkin-packages:
      - talker
      - listener
    build-packages:
      - libc6

  run-system:
    plugin: dump
    stage: [bin/run-system]
    prime: [bin/run-system]
